"use client";

// Joy + MUI bridge for MDX files. MDX should import from here only.
import {
  // primitives
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  Tabs,
  TabList,
  Tab as TabsTrigger,
  TabPanel as TabsContent,
  Alert,
  AlertDescription,
  Divider as Separator,
  Chip as Badge,
} from "@/components/ui/joy";

// Icons mapped to names used in MDX content
import {
  Security as Shield,
  Bolt as Zap,
  Groups as Users,
  Code,
  Layers,
  PlayArrow as Play,
  GitHub as Github,
  Launch as ExternalLink,
  CheckCircle,
  Star,
  ArrowForward as ArrowRight,
  Storage as Database,
  Lock,
  Psychology as Brain,
  Visibility as Eye,
  VisibilityOff as EyeOff,
  WarningAmber as AlertTriangle,
  Description as FileText,
  Settings,
  VpnKey as Key,
  // Additional icons for MDX files
  Cancel as XCircle,
  Terminal,
  Message as MessageSquare,
  CloudUpload as Upload,
  Schedule as Clock,
  CloudDownload as Download,
  ContentCopy as Copy,
  Search,
  AccountTree as Workflow,
  Source as GitBranch,
  Computer as Server,
  MenuBook as BookOpen,
} from "@mui/icons-material";

// Mermaid passthrough
export { Mermaid } from "@/components/Mermaid";

// Re-exports for MDX usage
export {
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  Tabs,
  TabList,
  TabsTrigger,
  TabsContent,
  Alert,
  AlertDescription,
  Separator,
  Badge,
  // icons
  Shield,
  Zap,
  Users,
  Code,
  Layers,
  Play,
  Github,
  ExternalLink,
  CheckCircle,
  Star,
  ArrowRight,
  Database,
  Lock,
  Brain,
  Eye,
  EyeOff,
  AlertTriangle,
  FileText,
  Settings,
  // Additional icons
  XCircle,
  Terminal,
  MessageSquare,
  Upload,
  Clock,
  Download,
  Copy,
  Search,
  Workflow,
  GitBranch,
  Server,
  BookOpen,
};
